name: 'Dependency Review'
on: [pull_request]
permissions:
  contents: write
  pull-requests: write
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: Maven Dependency Tree Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4.2.5
        with:
          fail-on-severity: moderate
          #otherwise - to not fail and see results:
          #warn-only: true
          deny-licenses: LGPL-2.0, BSD-2-Clause
          comment-summary-in-pr: true
